### ISSUE TITLE
How do I make axes such that more negative values are downward?

### ISSUE THREAD

**Issue by llmpandori** [njsilbiger/Lets_Code#2]
I can't think of a more intelligent way to phrase this question, but I was wondering how to make more negative values be farther down on the chart instead of farther up. I am also not sure how this works yet, since I have yet to use github. I have included a picture of the chart and the code I used to make it. It is LRR values (not bootstrapped yet) for live stages of marine invertebrates. 

allbarplot<-barplot(All.Raw.Data.Mean$Raw.LRR.mean, names.arg = unique(All.Raw.Data.Mean$LifeStage), ylim = c(0, -6), xlab = "Life Stage", ylab = "LRR", main = "Temp x Survival: Pooled LRR Average +/- SE - Raw Data", col = c("mediumvioletred", "seagreen", "mediumturquoise", "midnight blue"))

# now add error bars
arrows(allbarplot, (All.Raw.Data.Mean$Raw.LRR.mean + All.Raw.Data.Mean$Raw.LRR.SE), allbarplot, (All.Raw.Data.Mean$Raw.LRR.mean - All.Raw.Data.Mean$Raw.LRR.SE), angle = 90, code = 3, length = 0.05)

![issuecode](https://cloud.githubusercontent.com/assets/25216467/22094403/0852144a-ddc2-11e6-9a8b-787c71667577.JPG)

**Comment by njsilbiger** [comment]
Thanks for posting! The issue is that you have your ylim values set from 0 to -6 instead of -6 to 0.  try changing your code to ylim=c(-6,0) and it should solve the trick. :) Post back to let me know if that worked.

**Comment by llmpandori** [comment]
Worked great!
![image](https://cloud.githubusercontent.com/assets/25216467/22094551/15e678e8-ddc3-11e6-8a7e-e0df04302893.png)
